openapi: "3.0.2"
info:
  title: Shope API - OpenAPI v3.0.2
  version: "1.1.0"
  description: |
    **Shope** is a simple shop that is used for Sun* Atlas - Performance Testing training purposes. You can browse products, add them to your cart and buy them.

    You can visit the demo website by clicking on the link below:
    - Web: [https://shope.sun-asterisk.vn](https://shope.sun-asterisk.vn)
    - API: [https://shopeapi.sun-asterisk.vn](https://shopeapi.sun-asterisk.vn)
    - Grafana dashboard: [https://dash.sun-asterisk.vn](https://dash.sun-asterisk.vn)

    **Notes for SwaggerUI**:
    - Cookie authentication is currently not supported for "try it out" requests due to browser security restrictions. See [this issue](https://github.com/swagger-api/swagger-js/issues/1163) for more information.
    - Basic authentication is not included in the OPTIONS requests. Therefore, all preflight requests from SwaggerUI will be unauthorized and you will get CORS error.
    - If you want to use "try it out" feature with basic authentication and cookie authentication, you can add the requests headers manually using the browser extension [simple-modify-headers](https://chromewebstore.google.com/detail/simple-modify-headers/gjgiipmpldkpbdfjkgofildhapegmmic):
      1. URL pattern: `https://shopeapi1.sun-asterisk.vn/*`
      2. Add - Authorization - Basic <base64_token>
      3. Add - Cookie - shope_auth=<access_token>
      4. Click `Start` button
  contact:
    email: nguyen.huu.kim@sun-asterisk.com
servers:
  - url: https://shopeapi.sun-asterisk.vn
  - url: http://localhost:3000
tags:
  - name: accounts
    description: Everthing related to the accounts (login, register...).
  - name: products
    description: Everything related to the products.
  - name: carts
    description: Everything related to the carts.
  - name: orders
    description: Everything related to the orders.
paths:
  /auth/login:
    post:
      summary: Sign in by username and password
      tags:
        - accounts
      description: Get access token (JWT token) by username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "username"
                - "password"
              properties:
                username:
                  type: string
                  example: customer1935
                password:
                  type: string
                  example: 12345678
      responses:
        "200":
          description: Login successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTVkODIyZGE5YmQ1ZmUwODA5ODViYWUiLCJwcmVmZXJlZF91c2VybmFtZSI6ImN1c3RvbWVyMTkzNSIsInBpY3R1cmUiOiJodHRwczovL2ltYWdlcy52aWJsby5hc2lhL2F2YXRhci9hNjQ3MjMwZC02NzE4LTQyNDktYjdjYS0wOWM5NjBiMmU5N2MucG5nIiwiYXVkIjoic2hvcGUiLCJleHAiOjE3MDE2ODc0MTc4MjgsImlhdCI6MTcwMTY4MDIxNzgyOH0.fCaJ38l98nq2bKfdg7lvQDuri66fckdMJEl5g-1jJXI
                  expiredAt:
                    type: number
                    example: 1701687417842
        "400":
          $ref: "#/components/responses/400BadRequest"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /auth/register:
    post:
      summary: "Register a new account"
      description: "Register a new account."
      tags:
        - accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "username"
                - "password"
                - "confirmPassword"
              properties:
                username:
                  type: string
                  example: customer1935
                password:
                  type: string
                  example: 12345678
                confirmPassword:
                  type: string
                  example: 12345678
      responses:
        "200":
          description: Get user profile successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  username:
                    type: string
        "400":
          $ref: "#/components/responses/400BadRequest"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /auth/user:
    get:
      summary: "Get user profile information"
      description: "Get user profile information."
      tags:
        - accounts
      responses:
        "200":
          description: Get user profile successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  authUser:
                    $ref: "#/components/schemas/User"
                  cartItems:
                    type: number
                    example: 3
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /products/latest:
    get:
      summary: "Get products"
      description: "Get list of the latest products."
      tags:
        - products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  nextCursor:
                    type: string
                    example: 655d7f2c4e7abfc3da0ea224
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /products/{productId}:
    get:
      summary: "Get product details"
      description: "Get product details."
      tags:
        - products
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        "200":
          description: Get product successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /cart:
    delete:
      summary: "Reset your cart"
      description: "Make make your cart empty."
      tags:
        - carts
      responses:
        "200":
          description: Reset cart successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
    get:
      summary: "Get cart items"
      description: "Get cart items."
      tags:
        - carts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        product:
                          $ref: "#/components/schemas/Product"
                        quantity:
                          type: integer
                          example: 2
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /cart/item/{productId}:
    post:
      summary: "Add a product into your cart"
      description: "Add a product into your cart."
      tags:
        - carts
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        "200":
          $ref: "#/components/responses/200UpdateCartOK"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
    delete:
      summary: "Remove a product from your cart"
      description: |
        Remove a product from your cart. Before: Product A, quantity = 2. After:** Product A, quantity = 1.
      tags:
        - carts
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        "200":
          $ref: "#/components/responses/200UpdateCartOK"
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /cart/checkout:
    get:
      summary: "Get checkout information"
      description: Get checkout information.
      tags:
        - orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    example: 2043.00
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        product:
                          $ref: "#/components/schemas/Product"
                        quantity:
                          type: integer
                          example: 3
                        amount:
                          type: number
                          example: 2043.00
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
    post:
      summary: "Submit a new order"
      description: Submit a new order.
      tags:
        - orders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: Hanoi, Vietnam
      responses:
        "200":
          description: Create order successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  orderId:
                    type: string
                    example: 656dcf5057bc53f90ed744fc
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
  /orders:
    get:
      summary: "Get order history"
      description: Return list of recent orders.
      tags:
        - orders
      parameters:
        - name: cursor
          description: The cursor is used to query data for the next page
          in: query
          schema:
            type: string
            example: 656dcf5057bc53f90ed744fc
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  nextCursor:
                    type: string
                    example: 656dcf5057bc53f90ed744fc
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          description: Order ID
                          type: string
                          example: 2596dcf5057bc53f90ed744fc
                        items:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                                example: 2596dcf5057bc53f90ed744fc
                              product:
                                $ref: "#/components/schemas/Product"
                              quantity:
                                type: integer
                                example: 1
                              amount:
                                type: number
                                example: 681.00
                        total:
                          type: number
                          example: 681.00
                        address:
                          type: string
                          example: Hanoi, Vietnam
                        createdAt:
                          type: string
                          example: 2023-11-22T04:10:20.325Z
                        updatedAt:
                          type: string
                          example: 2023-11-22T04:10:20.325Z
        "400":
          $ref: "#/components/responses/400BadRequest"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "500":
          $ref: "#/components/responses/500InternalServer"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: shope_auth
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 655d822da9bd5fe080985bae
        username:
          type: string
          example: customer1935
        avatarUrl:
          type: string
          example: null
    Product:
      type: object
      properties:
        _id:
          type: string
          example: 655d7f2c4e7abfc3da0ea22f
        title:
          type: string
          example: Luxurious Granite Car
        description:
          type: string
          example: The beautiful range of Apple Natural√© that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients
        imageUrl:
          type: string
          example: https://loremflickr.com/170/170?lock=6447847631224832
        price:
          type: number
          example: 681
        discount:
          type: number
          example: 1
        createdAt:
          type: string
          example: 2023-11-22T04:10:20.325Z
        updatedAt:
          type: string
          example: 2023-11-22T04:10:20.325Z
        __v:
          type: string
          example: 0
          description: Data version
  parameters:
    ProductId:
      description: "Product ID in the path."
      name: productId
      in: path
      required: true
      schema:
        type: string
        example: 655d7f2c4e7abfc3da0ea22f
  responses:
    200UpdateCartOK:
      description: Update cart successfully.
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              count:
                type: number
                example: 1
                description: Count your cart by product ID.
    404NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: Route not found
    400BadRequest:
      description: "The request is invalid. For example: invalid bearer token format, invalid payload data..."
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 400
              error:
                type: string
                example: Bad Request
              message:
                type: string
                example: Your request is invalid
    401Unauthorized:
      description: "Can not authenticate your request."
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 401
              code:
                type: string
                example: FST_JWT_NO_AUTHORIZATION_IN_COOKIE
              error:
                type: string
                example: Unauthorized
              message:
                type: string
                example: No Authorization was found in request.cookies
    500InternalServer:
      description: "Something went wrong due to the server."
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
                example: 500
              error:
                type: string
                example: Internal Server Error
              message:
                type: string
                example: Something went wrong

security:
  - basicAuth: []
  - cookieAuth: []
  - bearerAuth: []
